name: dart_torrent_handler_example
description: Demonstrates how to use the dart_torrent_handler plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dart_torrent_handler:
    path: ../
  path_provider: ^2.1.0
  permission_handler: ^12.0.0+1
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Upgraded to match the plugin version

flutter:
  uses-material-design: true
